#!/bin/sh

backup_freebsd()
{
    # backup old files from FreeBSD base system
    for tocopy in $(ls /usr/local/share/freebsd/common-installed-settings/base/override/boot) ; do
       if [ -f /boot/$tocopy ]; then
            cp -af /boot/$tocopy /usr/local/share/freebsd/common-installed-settings/base/backup/boot/
        fi
    done
    # backup files from etc
    for tocopy in $(ls /usr/local/share/freebsd/common-installed-settings/base/override/etc)     ; do
       if [ -f /etc/$tocopy ]; then
            cp -af /etc/$tocopy /usr/local/share/freebsd/common-installed-settings/base/backup/etc/
        fi
    done
    # backup desktop files that will be override
    for files in $(ls /usr/local/share/freebsd/common-installed-settings/packages/override/etc/X11) ; do
        if [ -f /etc/X11/$files ]; then
            cp -af  /etc/X11/$files /usr/local/share/freebsd/common-installed-settings/packages/backup/etc/X11
        fi
    done

}

freebsd_overrides()
{
    cp -af /usr/local/share/freebsd/common-installed-settings/base/override/* /
}

packages_overrides()
{
    cp -af /usr/local/share/freebsd/common-installed-settings/packages/override/etc/* /etc
}

patch_etc_files()
{

    if [ -z "$(cat /boot/loader.conf | grep loader_brand)" ]; then
        cat /usr/local/share/freebsd/common-installed-settings/base/patches/boot/loader.conf.extra >> /boot/loader.conf
    fi

    if [ -z "$(cat /etc/profile | grep CHARSET)" ] ; then
        cat /usr/local/share/freebsd/common-installed-settings/base/patches/etc/profile.extra >> /etc/profile
    fi

    if [ -z "$(cat /etc/devfs.rules | grep devfsrules)" ] ; then
        cat /usr/local/share/freebsd/common-installed-settings/base/patches/etc/devfs.rules.extra >> /etc/devfs.rules
    fi

    if [ -z "$(cat /etc/make.conf | grep WITH_CUPS)" ] ; then
        cat /usr/local/share/freebsd/common-installed-settings/base/patches/etc/make.conf.extra >> /etc/make.conf
    fi

    if [ -z "$(cat /etc/rc.conf | grep powerd_enable)" ] ; then
        cat /usr/local/share/freebsd/common-installed-settings/base/patches/etc/rc.conf.extra >> /etc/rc.conf
    fi

    if [ -z "$(cat /etc/devd.conf| grep ugen[0-9])" ] ; then
         cat /usr/local/share/freebsd/common-installed-settings/base/patches/etc/devd.conf.extra >> /etc/devd.conf
    fi

    if [ -z "$(cat /etc/sysctl.conf | grep vfs.usermount)" ] ; then
         cat /usr/local/share/freebsd/common-installed-settings/base/patches/etc/sysctl.conf.extra >> /etc/sysctl.conf
    fi

}

packages_settings()
{
    #set htmlview alternative to firefox for cups
    if [ -e /usr/local/bin/firefox ] ; then
        update-alternatives --altdir /usr/local/etc/alternatives --install /usr/local/bin/htmlview htmlview /usr/local/bin/firefox 50
    fi
}

case "$2" in
    POST-INSTALL)
    # backup old files from FreeBSD base system
    backup_freebsd
    # copy files from override to FreeBSD base system
    freebsd_overrides
    # copy files from base direct over FreeBSD base system
    packages_overrides
    # patch files from etc
    patch_etc_files
    # apply packages settings
    packages_settings
    ;;
    *)
    ;;
esac

exit 0
