# Created by:	Eric Turgeon ericturgeon@ghostbsd.org
# Date created:	November 11 2013


PORTNAME=	fbi
PORTVERSION=	1.0
PORTREVISION=	0
CATEGORIES=	sysutils
MASTER_SITES=	https://github.com/wallisonalves/${PORTNAME}/archive/

MAINTAINER=	ericturgeon@ghostbsd.org
COMMENT=	FBI is the FreeBSD front end user interface for pc-sysinstall.

LICENSE=	BSD

USE_GITHUB=	yes
GH_ACCOUNT=	wallisonalves

USES = python:2
USE_PYTHON=	distutils
USE_GNOME=	pygtk2

.include <bsd.port.mk>
