#!/bin/sh

[ "$2" = 'POST-DEINSTALL' ] || exit 0

if [ -f /usr/local/etc/slim.conf ] ; then
        sed -i '' -e "s/auto_login          yes/#auto_login          no/g"\
            -e  "s/default_user        freebsd/#default_user        simone/g" \
            -e  "s/current_theme       freetbsd/current_theme       default/g" \
            /usr/local/etc/slim.conf
fi

exit 0

