#!/bin/sh

case "$2" in
    POST-INSTALL)
    # copy dmrc from freebsd dir to /usr/share/skel
    cp -af /usr/local/share/freebsd/mate-installed-settings/etc/skel/dmrc /usr/share/skel/dot.dmrc

    # copy grub config 
    if [ ! -d /usr/local/etc/default ]; then
        mkdir -p /usr/local/etc/default
    fi
    cp -af /usr/local/share/freebsd/mate-installed-settings/etc/default/*   /usr/local/etc/default

    #copy local policy 
    if [ ! -d /usr/local/etc/polkit-1 ]; then
        mkdir -p /usr/local/etc/polkit-1
    fi
    cp -af /usr/local/share/freebsd/mate-installed-settings/etc/polkit-1/* /usr/local/etc/polkit-1

    # set x-terminal-emulator alternative for gksu
    if [ -e /usr/local/bin/mate-terminal ] ; then
        update-alternatives --altdir /usr/local/etc/alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/mate-terminal 50
    fi
    ;;
esac

exit 0
